server:
  port: 8080

mybatis:
  typeAliasesPackage: com.example.springboot_sqlserver.bean
  mapperLocations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databasename=lll
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123456

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/



##pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


